backslash

diff --git a/.github/workflows/ci_tests_linux.yml b/.github/workflows/ci_tests_linux.yml
--- a/.github/workflows/ci_tests_linux.yml
+++ b/.github/workflows/ci_tests_linux.yml
@@ -30,9 +30,9 @@ jobs:
       - name: Style Check
         # The solo " in below bash call is an escape character for :
         run: |
-          .github/scripts/code_style.sh check || ( |
-          echo -e '::error There are files which do not adhere to the coding style. |
-          Please see directions to fix this here:" https://github.com/Azure/azure-iot-middleware-freertos#code-style' |
+          .github/scripts/code_style.sh check || ( \
+          echo -e '::error There are files which do not adhere to the coding style. \
+          Please see directions to fix this here:" https://github.com/Azure/azure-iot-middleware-freertos#code-style' \
           && exit 1 )
         if: >-
           (
