add exit

diff --git a/.github/workflows/ci_tests_linux.yml b/.github/workflows/ci_tests_linux.yml
--- a/.github/workflows/ci_tests_linux.yml
+++ b/.github/workflows/ci_tests_linux.yml
@@ -28,7 +28,7 @@ jobs:
           ( github.event.pull_request.head.repo.fork == true )
 
       - name: Style Check
-        run: .github/scripts/code_style.sh check || echo -e '::error There are files which do not adhere to the coding style. Please see directions to fix this here:" https://github.com/Azure/azure-iot-middleware-freertos#code-style'
+        run: .github/scripts/code_style.sh check || echo -e '::error There are files which do not adhere to the coding style. Please see directions to fix this here:" https://github.com/Azure/azure-iot-middleware-freertos#code-style && exit 1'
         if: >-
           (
             github.event_name == 'pull_request' &&
